name: agriesg
description: "AgriESG Food Optimisation Engine"
publish_to: 'none'
version: 0.1.0+6

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  fl_chart: ^1.2.0
  hugeicons: ^1.1.6
  http: ^1.6.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/food_knowledge_dataset.csv
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
          weight: 400
        - asset: assets/fonts/Inter.ttf
          weight: 500
        - asset: assets/fonts/Inter.ttf
          weight: 600
        - asset: assets/fonts/Inter.ttf
          weight: 700
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit.ttf
          weight: 500
        - asset: assets/fonts/Outfit.ttf
          weight: 600
        - asset: assets/fonts/Outfit.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
